### ISSUE TITLE
Missing training files

### ISSUE THREAD

**Issue by zyfone** [AmineMarnissi/UDAT#3]
Can you provide the training file of train_net.py?
Or can you send it to my email address?
zyfone.cs@gmail.com
Thanks

**Comment by Genie-Kim** [comment]
Can you share the training file of train_net.py?
Or can you send it to my email, please?

[kimjin928@yonsei.ac.kr](mailto:kimjin928@yonsei.ac.kr)
Thank you for reading

**Comment by AmineMarnissi** [comment]
The train_net.py file has been uploaded. You can access it now. Thank you

**Comment by Genie-Kim** [comment]
Thank you for your fast response!
